config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'dashboard#index', as: :dashboard

    get :login, to: 'sessions#new', as: :login
    post :login, to: 'sessions#create'
    get :logout, to: 'sessions#destroy', as: :logout

    resources :staffs, except: [:show]
    resources :roles
  end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :role
  has_many :staffs, through: :role

  validates :resource, presence: true
  validates :action, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  RESERVED = %w(admin)

  has_many :permissions, dependent: :destroy
  has_and_belongs_to_many :staffs

  validates :name, presence: true, uniqueness: true

  scope :editable, -> { where.not(name: RESERVED ) }
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  has_secure_password

  has_and_belongs_to_many :roles
  has_many :permissions, through: :roles

  validates :name, presence: true, uniqueness: true

  before_update :ensure_admin_exists
  before_destroy :ensure_not_admin

  scope :admin, -> { joins(:roles).where('roles.name' => 'admin') }

  def ensure_admin_exists
    unless Staff.admin.exists?
      errors.add(:base, 'There is only one admin left.')
      return false
    end
  end

  def ensure_not_admin
    if has_role?('admin')
      errors.add(:base, 'Admin can not be deleted.')
      return false
    end
  end

  def has_role?(role)
    if role.is_a?(Role)
      roles.exists?(role)
    else
      roles.exists?(name: role)
    end
  end

  def add_role(role)
    role = role.is_a?(Role) ? role : Role.find_by_name!(role)
    roles << role unless has_role?(role)
  end

  def remove_role(role)
    role = role.is_a?(Role) ? role : Role.find_by_name!(role)
    roles.delete(role) if has_role?(role)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < AppController
  include Pundit

  layout 'admin'
  helper_method :current_staff

  before_action :authenticate_staff!

  rescue_from Pundit::NotAuthorizedError, with: :unauthorized

  private

  def current_staff
    @current_staff ||= Staff.find(session[:staff_id]) if session[:staff_id]
  end
  alias_method :pundit_user, :current_staff

  def authenticate_staff!
    redirect_to admin_login_path, alert: 'You need to login first.' if current_staff.nil?
  end

  def unauthorized
    redirect_to request.referrer || admin_dashboard_path, alert: 'You are not authorized to perform this action.'
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < BaseController
    def index
    end
  end
end

app/controllers/admin/roles_controller.rb
module Admin
  class RolesController < BaseController
    def index
      authorize Role
      @roles = policy_scope(Role).editable
    end

    def show
      @role = Role.editable.find(params[:id])
      authorize @role
    end

    def new
      @role = Role.new
      authorize @role
    end

    def create
      @role = Role.new(role_params)
      authorize @role
      if @role.save
        redirect_to [:admin, @role], notice: 'Role created.'
      else
        render 'new'
      end
    end

    def edit
      @role = Role.editable.find(params[:id])
      authorize @role
    end

    def update
      @role = Role.editable.find(params[:id])
      authorize @role
      if @role.update(role_params)
        redirect_to [:admin, @role], notice: 'Role updated.'
      else
        render 'edit'
      end
    end

    def destroy
      @role = Role.editable.find(params[:id])
      authorize @role
      @role.destroy
      redirect_to admin_roles_path
    end

    private

    def role_params
      role_params = params.require(:role).permit(:name, permissions: [])
      role_params[:permissions] = build_permissions(role_params[:permissions] || [])
      role_params
    end

    def build_permissions(permissions)
      parse_permissions(permissions).collect do |permission|
        if @role.nil?
          Permission.new(permission)
        else
          @role.permissions.find_or_initialize_by(permission)
        end
      end
    end

    def parse_permissions(permissions)
      permissions.collect do |permission|
        action, resource = permission.split('#', 2)
        { action: action, resource: resource }
      end
    end
  end
end

app/controllers/admin/sessions_controller.rb
module Admin
  class SessionsController < BaseController
    skip_before_action :authenticate_staff!

    def new
    end

    def create
      staff = Staff.find_by_name(params[:name])
      if staff && staff.authenticate(params[:password])
        session[:staff_id] = staff.id
        redirect_to admin_dashboard_path, notice: 'Logged in.'
      else
        flash.now.alert = 'Name or password is invalid.'
        render 'new'
      end
    end

    def destroy
      session[:staff_id] = nil
      redirect_to admin_login_path, notice: 'Logged out.'
    end
  end
end

app/controllers/admin/staffs_controller.rb
module Admin
  class StaffsController < BaseController
    def index
      authorize Staff
      @staffs = policy_scope(Staff).includes(:roles)
    end

    def new
      @staff = Staff.new
      authorize @staff
    end

    def create
      @staff = Staff.new(staff_params)
      authorize @staff
      if @staff.save
        redirect_to admin_staffs_path, notice: 'Staff created.'
      else
        render 'new'
      end
    end

    def edit
      @staff = Staff.find(params[:id])
      authorize @staff
    end

    def update
      @staff = Staff.find(params[:id])
      authorize @staff
      if @staff.update(staff_params)
        redirect_to admin_staffs_path, notice: 'Staff updated.'
      else
        render 'edit'
      end
    end

    def destroy
      @staff = Staff.find(params[:id])
      authorize @staff
      unless @staff.destroy
        flash[:alert] = @staff.errors.full_messages.join(', ')
      end
      redirect_to admin_staffs_path
    end

    private

    def staff_params
      params.require(:staff).permit(:name, :password, :password_confirmation, role_ids: [])
    end
  end
end

app/controllers/app_controller.rb
class AppController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/application_controller.rb
class ApplicationController < AppController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Welcome!</h1>

app/views/admin/roles/_form.html.erb
<%= form_for [:admin, role] do |f| %>
  <% if @role.errors.any? %>
    <div>
      <ul>
        <% @role.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :permissions %><br />
    <% ApplicationPolicy.policies.each do |policy| %>
      <% resource = policy.resource %>
      <div>
        <span><%= resource %></span>
        <% policy.actions.each do |action| %>
          <% checked = role.permissions.exists?(action: action, resource: resource) %>
          <% value = "#{action}##{resource}" %>
          <%= f.check_box :permissions, { multiple: true, checked: checked }, value, nil %>
          <%= f.label :permissions, value, value: value %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div><%= f.submit %></div>
<% end %>

app/views/admin/roles/edit.html.erb
<h1>Edit Role</h1>

<%= render partial: 'form', locals: { role: @role } %>

app/views/admin/roles/index.html.erb
<%= link_to 'New Role', new_admin_role_path if policy(Role).create? %>

<table>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>
  <% @roles.each do |role| %>
    <tr>
      <td><%= role.name %></td>
      <td>
        <%= link_to 'Show', admin_role_path(role) if policy(Role).read? %>
        <%= link_to 'Edit', edit_admin_role_path(role) if policy(Role).update? %>
        <%= link_to 'Delete', admin_role_path(role), method: :delete if policy(Role).destroy? %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/roles/new.html.erb
<h1>New Role</h1>

<%= render partial: 'form', locals: { role: @role } %>

app/views/admin/roles/show.html.erb
<h1><%= @role.name %></h1>

<ul>
  <% @role.permissions.each do |permission| %>
    <li><%= permission.action %>#<%= permission.resource %></li>
  <% end %>
</ul>

app/views/admin/staffs/_form.html.erb
<%= form_for [:admin, staff] do |f| %>
  <% if staff.errors.any? %>
    <div>
      <ul>
        <% staff.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :roles %><br />
    <%= f.collection_check_boxes :role_ids, Role.all, :id, :name %>
  </div>
  <div><%= f.submit %></div>
<% end %>

app/views/admin/staffs/edit.html.erb
<h1>New Staff</h1>

<%= render partial: 'form', locals: { staff: @staff } %>

app/views/admin/staffs/index.html.erb
<%= link_to 'New Staff', new_admin_staff_path if policy(Staff).create? %>

<table>
  <tr>
    <th>Name</th>
    <th>Roles</th>
    <th>Actions</th>
  </tr>
  <% @staffs.each do |staff| %>
    <tr>
      <td><%= staff.name %></td>
      <td><%= staff.roles.collect(&:name).join(', ') %></td>
      <td>
        <%= link_to 'Edit', edit_admin_staff_path(staff) if policy(Staff).update? %>
        <%= link_to 'Delete', admin_staff_path(staff), method: :delete if policy(Staff).destroy? %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/staffs/new.html.erb
<h1>New Staff</h1>

<%= render partial: 'form', locals: { staff: @staff } %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oh My User | Admin</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div>
      <% unless current_staff.nil? %>
        <strong><%= current_staff.name %></strong>
        <%= link_to 'Dashboard', admin_dashboard_path %>
        <%= link_to 'Staffs', admin_staffs_path if policy(Staff).read? %>
        <%= link_to 'Roles', admin_roles_path if policy(Role).read? %>
        <%= link_to 'Logout', admin_logout_path %>
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oh My User</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>